from telegram import Update
from telegram.ext import ContextTypes

from utils.decorators import deprecated, description, example, triggers, usage


@usage("/mj")
@example("/mj")
@triggers(["mj"])
@description("Return a random image generated by MidJourney.")
@deprecated(
    "This command has been deprecated due to technical issues. "
    "Contact @obviyus if you have a use case for this command."
)
async def transcribe(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """
    Transcribe an audio message.
    """
    if transcribe.deprecated:
        await update.message.reply_text(transcribe.deprecated)
        return
