from telegram import Update
from telegram.ext import ContextTypes

from utils.decorators import deprecated, description, example, triggers, usage


@usage("/mj")
@example("/mj")
@triggers(["mj"])
@description("Return a random image generated by MidJourney.")
@deprecated(
    "This command has been deprecated due to technical issues. "
    "Contact @obviyus if you have a use case for this command."
)
async def midjourney(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """
    Return a random image generated by MidJourney.
    """
    if midjourney.deprecated:
        await update.message.reply_text(midjourney.deprecated)
        return
